package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class DatingController implements Initializable{
	private Stage stage;
	private Scene scene;
	private Parent root;
	 @FXML
    private TextField AgeField;

    @FXML
    private TextField BookField;

    @FXML
    private Button BtnPost;

    @FXML
    private TextField CelebrityField;

    @FXML
    private TextField ContactFBField;

    @FXML
    private TextField ContactIGField;

    @FXML
    private CheckBox DrinkingCheck;

    @FXML
    private VBox Layout;

    @FXML
    private TextField MBTIField;

    @FXML
    private TextField MovieField;

    @FXML
    private TextField MusicField;

    @FXML
    private TextField NameField;

    @FXML
    private CheckBox NonDrinkingCheck;

    @FXML
    private CheckBox NonSmokingCheck;

    @FXML
    private TextField PasswordField;

    @FXML
    private DatePicker PostDatePicker;

    @FXML
    private TextArea PostDescriptionField;

    @FXML
    private TextField PostLocationField;

    @FXML
    private TextField PostPeopleField;

    @FXML
    private TextField PostTimeField;

    @FXML
    private TextField PostTitleField;

    @FXML
    private ChoiceBox<String> PurposeChoice;

    @FXML
    private TextField SexualPerferenceField;

    @FXML
    private CheckBox SmokingCheck;

    @FXML
    private Label UserIDLabel;

    @FXML
    private ImageView UserImage;

    @FXML
    private Label UserNameLabel;

    @FXML
    private Button btnEditprofile;

    @FXML
    private Button btnSaveChanges;

    @FXML
    private Button btndating;

    @FXML
    private Button btnpasswordchange;

    @FXML
    private Button btnposting;

    @FXML
    private Button btnprofile;

    @FXML
    private Button btnsetting;

    @FXML
    private AnchorPane datingpage;

    @FXML
    private TextField departmentField;

    @FXML
    private TextField gradeField;

    @FXML
    private Button logout;

    @FXML
    private AnchorPane postingpage;

    @FXML
    private AnchorPane profilepage;

    @FXML
    private AnchorPane settingpage;
    
    private Profile profile;

    @FXML
    public void btnchangesaving(ActionEvent event) {

    }
    
    @FXML
    public void btneditprofile(ActionEvent event) {

    }
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		PurposeChoice.getItems().addAll("純交友","找另一半","就玩玩");
		
		List<Activity> activities = new ArrayList<>(activities());
		for(int i= 0; i< activities.size();i++) {
			FXMLLoader fxmlloader = new FXMLLoader();
			fxmlloader.setLocation(getClass().getResource("Activityitem.fxml"));
			
			try {
				HBox hbox = fxmlloader.load();
				ActivityitemController ac = fxmlloader.getController();
				ac.setData(activities.get(i));
				Layout.getChildren().add(hbox);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
	}
	
//	@FXML
//	public void btneditprofile(ActionEvent event) {
//		// TODO Autogenerated
//		profile = new Profile();
//		imageview = new ImageView(getClass().getResourceAsStream());
//	}
	@FXML
	public void btnpasswordsaving(ActionEvent event) {
		// TODO Autogenerated
		
	}
	
	@FXML
	private void handleclicked(ActionEvent event) {
		if(event.getSource()== btnprofile) {
			profilepage.toFront();
			
		}
		else if(event.getSource()== btnsetting) {
			settingpage.toFront();
			
		}
		else if(event.getSource()== btnposting) {
			postingpage.toFront();
		}
		else if(event.getSource()== btndating) {
			datingpage.toFront();
		}
		
	}
	@FXML
	private void logout(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("Login.fxml"));
		root = loader.load();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		Scene scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	@FXML
	private List<Activity> activities(){
		List<Activity> ls = new ArrayList<>();
		Activity acti1 = new Activity("8/8", "喝酒喝翻天", "emo怪一起喝酒吧", 2);
		Activity acti2 = new Activity("4/8", "坐taxi到北車", "需要有人分擔車費...霸脫", 3);
		Activity acti3 = new Activity("5/30", "誰可以陪我去看醫生", "沒有朋友願意陪我看醫生誰可以陪我去婦產科，女生佳", 1);
		Activity acti4 = new Activity("6/4", "看電影就對ㄌ", "有沒有人要去看玩命關頭10啊", 1);
		
		ls.add(acti1);
		ls.add(acti2);
		ls.add(acti3);
		ls.add(acti4);
		
	
		
		return ls;
		
	}
	
	
	
}


	